package lexer

import "github.com/jackie8tao/golua/pkg/ast"

var reservedWords = map[string]ast.TokenType{
	"and":      ast.TokenAnd,
	"break":    ast.TokenBreak,
	"do":       ast.TokenDo,
	"else":     ast.TokenElse,
	"elseif":   ast.TokenElseif,
	"end":      ast.TokenEnd,
	"false":    ast.TokenFalse,
	"for":      ast.TokenFor,
	"function": ast.TokenFunction,
	"if":       ast.TokenIf,
	"in":       ast.TokenIn,
	"local":    ast.TokenLocal,
	"nil":      ast.TokenNil,
	"not":      ast.TokenNot,
	"or":       ast.TokenOr,
	"repeat":   ast.TokenRepeat,
	"return":   ast.TokenReturn,
	"then":     ast.TokenThen,
	"true":     ast.TokenTrue,
	"until":    ast.TokenUntil,
	"while":    ast.TokenWhile,
}

var operators = map[string]ast.TokenType{
	"+":   ast.TokenAdd,
	"-":   ast.TokenSub,
	"*":   ast.TokenMul,
	"/":   ast.TokenDiv,
	"^":   ast.TokenPow,
	"=":   ast.TokenAssign,
	"~=":  ast.TokenNeq,
	"<=":  ast.TokenLeq,
	">=":  ast.TokenGeq,
	"<":   ast.TokenLt,
	">":   ast.TokenGt,
	"==":  ast.TokenEq,
	"(":   ast.TokenLparen,
	")":   ast.TokenRparen,
	"[":   ast.TokenLbracket,
	"]":   ast.TokenRbracket,
	"{":   ast.TokenLbrace,
	"}":   ast.TokenRbrace,
	";":   ast.TokenSemicolon,
	",":   ast.TokenComma,
	":":   ast.TokenColon,
	".":   ast.TokenDot,
	"..":  ast.TokenDotDot,
	"...": ast.TokenDots,
}

var tokenNames = map[ast.TokenType]string{
	ast.TokenEOF:        "TK_EOF",
	ast.TokenIdentifier: "TK_IDENTIFIER",
	ast.TokenNumber:     "TK_NUMBER",
	ast.TokenString:     "TK_STRING",
	ast.TokenAnd:        "TK_AND",
	ast.TokenBreak:      "TK_BREAK",
	ast.TokenDo:         "TK_DO",
	ast.TokenElse:       "TK_ELSE",
	ast.TokenElseif:     "TK_ELSEIF",
	ast.TokenEnd:        "TK_END",
	ast.TokenFalse:      "TK_FALSE",
	ast.TokenFor:        "TK_FOR",
	ast.TokenFunction:   "TK_FUNCTION",
	ast.TokenIf:         "TK_IF",
	ast.TokenIn:         "TK_IN",
	ast.TokenLocal:      "TK_LOCAL",
	ast.TokenNil:        "TK_NIL",
	ast.TokenNot:        "TK_NOT",
	ast.TokenOr:         "TK_OR",
	ast.TokenRepeat:     "TK_REPEAT",
	ast.TokenReturn:     "TK_RETURN",
	ast.TokenThen:       "TK_THEN",
	ast.TokenTrue:       "TK_TRUE",
	ast.TokenUntil:      "TK_UNTIL",
	ast.TokenWhile:      "TK_WHILE",
	ast.TokenAdd:        "TK_ADD",
	ast.TokenSub:        "TK_SUB",
	ast.TokenMul:        "TK_MUL",
	ast.TokenDiv:        "TK_DIV",
	ast.TokenPow:        "TK_POW",
	ast.TokenAssign:     "TK_ASSIGN",
	ast.TokenNeq:        "TK_NEQ",
	ast.TokenLeq:        "TK_LEQ",
	ast.TokenGeq:        "TK_GEQ",
	ast.TokenLt:         "TK_LT",
	ast.TokenGt:         "TK_GT",
	ast.TokenEq:         "TK_EQ",
	ast.TokenLparen:     "TK_LPAREN",
	ast.TokenRparen:     "TK_RPAREN",
	ast.TokenLbracket:   "TK_LBRACKET",
	ast.TokenRbracket:   "TK_RBRACKET",
	ast.TokenLbrace:     "TK_LBRACE",
	ast.TokenRbrace:     "TK_RBRACE",
	ast.TokenSemicolon:  "TK_SEMICOLON",
	ast.TokenComma:      "TK_COMMA",
	ast.TokenColon:      "TK_COLON",
	ast.TokenDot:        "TK_DOT",
	ast.TokenDotDot:     "TK_DOTDOT",
	ast.TokenDots:       "TK_DOTS",
}
